# aws cloudformation create-stack --profile bsejawal --template-file file://app-cluster.yml --stack-name appCluster
AWSTemplateFormatVersion: '2010-09-09'
Description: Container Cluster on ECS, loadbalancer, security groups and loadbalancer

Resources:

  ECRRepository:
    Type: 'AWS::ECR::Repository'   
    Properties:
      RepositoryName: 'bhesh-demo-ecr'

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: 'bhesh-demo-cluster'

  Loadbalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: 'ecs-services'
      Subnets: 
        - !ImportValue 'Subnet1'
        - !ImportValue 'Subnet2'
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  LoadBalancerListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref Loadbalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
            
  LoadBalancerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for loadbalancer to services on ECS
      VpcId: !ImportValue 'VPC'
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1

  DefaultTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: default
      VpcId: !ImportValue 'VPC'
      Protocol: 'HTTP'
      Port: '80'
  
  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: 'apis'
      RetentionInDays: 1

  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue 'VPC'
      GroupDescription: for ecs containers
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
          IpProtocol: -1

Outputs:
  
  Cluster:
    Value: !Ref ECSCluster
    Export:
      Name: 'ECSCluster'

  Listener:
    Description: Listerner port 80
    Value: !Ref LoadBalancerListener
    Export:
      Name: 'Listener'

  ContainerSecurityGroup:
    Description: Container Security Group
    Value: !Ref ContainerSecurityGroup
    Export:
      Name: 'ContainerSecurityGroup'
  
  LoadBalancerDNS:
    Description: Domain name for the loadbalancer
    Value: !GetAtt Loadbalancer.DNSName
    Export:
      Name: 'DomainName'

  EcrArn:
    Description: ARN of  for the ECR
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: 'EcrArn'
      
  LogGroup:
    Description: Log Group for ECR
    Value: !Ref CloudWatchLogsGroup
    Export:
      Name: 'LogGroup'